AndreasLrx/LaFlammeDivain

.github/workflows/mirroring.yml, .github/workflows/unity-build.yml
Introduce CI for building project and mirroring this repository to the Epitech private one.
Close #1 
Close #3
=> Add github workflows

Assets/Prefabs/Player.prefab, Assets/Prefabs/Player.prefab.meta, Assets/Scripts/Player.cs, Assets/Scripts/Player.cs.meta, Assets/Sprites/WhiteSquare.png, Assets/Sprites/WhiteSquare.png.meta
Add script for movable player 
Close #5
=> Add script for movable player

Assets/Prefabs/Enemies/Dummy.prefab, Assets/Prefabs/Enemies/Dummy.prefab.meta, Assets/Scripts/Dummy.cs, Assets/Scripts/Dummy.cs.meta
Create the first enemy who can't attack or move, he can lose HP and die.
Close #7
=> Create Dummy with script to take damage

.github/workflows/unity-build.yml, CONTRIBUTING.md
Add more specification to the commit naming convention.
Also comment out the WebGL build in the CI to speed up the CI process and the development cycle.
=> Update the contributing.md and comment out the WebGl build

Assets/Prefabs/GameManager.prefab, Assets/Scenes/GameScene.unity, Assets/Scripts/BoardManager.cs, Packages/manifest.json, Packages/packages-lock.json
Implement a camera which must follow the player when he moves. However the camera does not show areas outside the map.
Close #9
=> Add camera following the player

.gitignore, Packages/manifest.json, Packages/packages-lock.json
Add completion package for vscode ide.
=> Add com.unity.ide.vscode package for completion on VsCode IDE

Assets/Prefabs/GameManager.prefab, Assets/Prefabs/Player.prefab, Assets/Prefabs/Wisps/AttackWisp.prefab, Assets/Prefabs/Wisps/AttackWisp.prefab.meta, Assets/Prefabs/Wisps/WispsGroup.prefab, Assets/Prefabs/Wisps/WispsGroup.prefab.meta, Assets/Scripts/AttackWisp.cs, Assets/Scripts/AttackWisp.cs.meta, Assets/Scripts/BoardManager.cs, Assets/Scripts/Player.cs, Assets/Scripts/Wisp.cs, Assets/Scripts/Wisp.cs.meta, Assets/Scripts/WispsGroup.cs, Assets/Scripts/WispsGroup.cs.meta, ProjectSettings/InputManager.asset
Introduce general wisps behavior.
GameObject containing multiple wisps. The wisps orbit around this object. This object is expected as a child object of a Player/AI object.
Abstract base class for all specific wisps. Contains behavior of activation and attach/detach to parent WispsGroup. 
Handle the cooldown mechanic of the wisps as well as a temporary coloration to see whether the wisp can be activated or not.
Each wisp inheriting this class must implement the OnActivate/OnAttach/OnDetach method.
This wisp can be throw by the player by clicking on any direction. It (will) deal damages on its path.
You can add attack wisps to the player using the key 'A' (azerty keyboard). This is a debug action.
Close #12 
=> Wisp core system

Assets/Prefabs/2D Render Pipeline.asset, Assets/Prefabs/2D Render Pipeline.asset.meta, Assets/Prefabs/2D Renderer.asset, Assets/Prefabs/2D Renderer.asset.meta, Assets/Prefabs/Enemies/Dummy.prefab, Assets/Prefabs/Player.prefab, Assets/Prefabs/Tiles/Floor.prefab, Assets/Prefabs/Tiles/Wall.prefab, Assets/Prefabs/Wisps/AttackWisp.prefab, Assets/Scenes/GameScene.meta, Assets/Scenes/GameScene.unity, Assets/Scripts/Wisp.cs, Assets/UniversalRenderPipelineGlobalSettings.asset, Assets/UniversalRenderPipelineGlobalSettings.asset.meta, Packages/manifest.json, Packages/packages-lock.json, ProjectSettings/EditorSettings.asset, ProjectSettings/GraphicsSettings.asset, ProjectSettings/ShaderGraphSettings.asset, ProjectSettings/URPProjectSettings.asset
Introduced light sources for player and wisps.
Make global light really dark, may be changed later.
Now use unity Universal Rendering Pipeline (URP) to allow usage of the light engine.
Close #41
=> Introduce light

Assets/Prefabs/Tiles/Wall.prefab, Assets/Scripts/AttackWisp.cs, ProjectSettings/TagManager.asset
Add attack function for attack wisp when wisp hit a wall or enemy it comes back to the player 
Close #33
=> add attack for wisp and collision when hit a object

Assets/Prefabs/GameManager.prefab, Assets/Prefabs/Wisps/AttackWisp.prefab, Assets/Prefabs/Wisps/PoisonWisp.prefab, Assets/Prefabs/Wisps/PoisonWisp.prefab.meta, Assets/Scripts/AttackWisp.cs, Assets/Scripts/Player.cs, Assets/Scripts/PoisonWisp.cs, Assets/Scripts/PoisonWisp.cs.meta, Assets/Scripts/Wisp.cs
Add poison wisp who leaves a poison trail on the ground
Close #48 
Remove Random color for AttackWisp
Pass _Color in wisp file to a Serialized Field
=> Add poison wisp

Assets/Prefabs/Wisps/AttackWisp.prefab, Assets/Prefabs/Wisps/PoisonWisp.prefab, Assets/Scripts/PoisonWisp.cs, Assets/Scripts/Wisp.cs
Add trail for attack wisp
Close #51
=> Add trail for wisp

.editorconfig, .github/workflows/unity-build.yml, Assets/Models.meta, Assets/Scripts/BoardManager.cs, Assets/Scripts/Dummy.cs, Assets/Scripts/MovingObject.cs, Assets/Scripts/Player.cs, Assets/Scripts/PoisonWisp.cs, CONTRIBUTING.md
Introduce a new workflow checking the scripts format. Updated the contributing file to the new coding style.
Close #53
Reformatted scripts with invalid format.
Made MovingObject Awake and Update method virtual and add override keywords in PoisonWisp equivalent method to avoid warnings.
=> Introduce new format checking workflow

Assets/Scripts/AttackWisp.cs, Assets/Scripts/PoisonWisp.cs, Assets/Scripts/Wisp.cs
Made trail changes (on detach/attach) smoothly instead of instantly as before.
Close #56
=> Introduce SmoothlyChangeTrailParameter method for more natural trail behavior

Assets/Prefabs/Enemies/Dummy.prefab, Assets/Scripts/AttackWisp.cs, Assets/Scripts/BoardManager.cs, Assets/Scripts/Dummy.cs, Assets/Scripts/Enemy.cs, Assets/Scripts/Enemy.cs.meta, Assets/Scripts/PoisonWisp.cs, Assets/Scripts/Weapon.cs
Add a base class for enemy 
Close #55
=> Add Enemy base class

Assets/Prefabs/Enemies/Dummy.prefab, Assets/Prefabs/GameManager.prefab, Assets/Scenes/GameScene.unity, Assets/Scripts/BoardManager.cs, ProjectSettings/InputManager.asset, ProjectSettings/QualitySettings.asset
Generate rooms procedurally. They have various sizes and obstacles.
Close #8 (issue)
=> Add generation of rooms procedurally

Assets/Prefabs/GameManager.prefab, Assets/Scripts/BoardManager.cs, Assets/Scripts/GameManager.cs, Assets/Scripts/Loader.cs, Assets/Scripts/Player.cs, Assets/Scripts/PrefabManager.cs, Assets/Scripts/PrefabManager.cs.meta, Assets/Scripts/Singleton.cs, Assets/Scripts/Singleton.cs.meta
Introduce a new templated Singleton class. GameManager, PrefabManager and Player classes are now singletons.
A singleton can be used this way:
```C#
if (Player.Instanciated())
Player.Instance.TakeDamage(5.f)
```
All the prefab gameobjects are moved in the PrefabManager Singleton instead of the BoardManager.
Close #65 
Reintroduce enemies in the room generation.
=> Refactor the Game Manager

Assets/Scripts/AsyncEventProcessor.cs, Assets/Scripts/AsyncEventProcessor.cs.meta, Assets/Scripts/Entities/Enemies/Dummy.cs, Assets/Scripts/Entities/Enemies/EliteEnemy.cs, Assets/Scripts/Entities/Enemies/Enemy.cs, Assets/Scripts/Entities/Enemies/FireEliteEnemy.cs, Assets/Scripts/Entities/Player/Player.cs, Assets/Scripts/Entities/Wisps/AttackWisp.cs, Assets/Scripts/Entities/Wisps/PoisonWisp.cs, Assets/Scripts/Entities/Wisps/Wisp.cs
Introduce a new script AsyncEventProcessor to allow combining multiple asynchronous event callbacks.
=> Introduce AsyncEventProcessor to simplify events through delegates

Assets/Prefabs/Wisps/BombWisp.prefab, Assets/Prefabs/Wisps/BombWisp.prefab.meta, Assets/Scripts/Entities/Wisps/BombWisp.cs, Assets/Scripts/Entities/Wisps/BombWisp.cs.meta, Assets/Scripts/Entities/Wisps/Wisp.cs
Add bomb wisp ,when wisp hit is explode and make a large circle for make damage for all enemy or player .
Close #70
=> Add a bomb wisp

Assets/Prefabs/Wisps/DefenseWisp.prefab, Assets/Prefabs/Wisps/DefenseWisp.prefab.meta, Assets/Scripts/Entities/Player/Player.cs, Assets/Scripts/Entities/Wisps/DefenseWisp.cs, Assets/Scripts/Entities/Wisps/DefenseWisp.cs.meta
Add defense wisp ,this wisp work like a armor when the player obtain a defense wisp we gain 1 point of armor we can hit one time and the wisp adsorb the hit for retrieve this armor point we just need to use the wisp but i have a long cool down  
Close #72
=> Add defense wisp

Assets/Scenes/GameScene.unity, Assets/Scenes/Menu.unity, Assets/Scripts/Entities/Enemies/FireElite.cs, Assets/Scripts/Entities/Player/PlayerController.cs, Assets/Scripts/Entities/Wisps/PoisonWisp.cs, Assets/Scripts/GameManager.cs, Assets/Scripts/PauseMenu.cs, Assets/Scripts/PauseMenu.cs.meta, Assets/Scripts/Singleton.cs
Add Pause Menu
Close #86
Fix HomeMenu image and default button
=> Add Pause menu

Assets/Prefabs/AICompanion.prefab, Assets/Prefabs/Enemies/Bone.prefab, Assets/Prefabs/Enemies/Bone.prefab.meta, Assets/Prefabs/Enemies/Skeleton.prefab, Assets/Prefabs/Enemies/Skeleton.prefab.meta, Assets/Prefabs/GameManager.prefab, Assets/Prefabs/Player.prefab, Assets/Scripts/Entities/Enemies/Enemy.cs, Assets/Scripts/Entities/Enemies/Skeleton.cs, Assets/Scripts/Entities/Enemies/Skeleton.cs.meta, Assets/Scripts/Entities/Projectile.cs, Assets/Scripts/Entities/Projectile.cs.meta, Assets/Scripts/PrefabManager.cs, Assets/Scripts/Singleton.cs
Introduce new skeleton enemy. It send projectiles to the player when close enough.
Close #95
=> Introduce new Skeleton enemy

Assets/Prefabs/Enemies/Ectoplasm.prefab, Assets/Prefabs/Enemies/Ectoplasm.prefab.meta, Assets/Prefabs/Enemies/Ghost.prefab, Assets/Prefabs/Enemies/Ghost.prefab.meta, Assets/Prefabs/GameManager.prefab, Assets/Prefabs/Player.prefab, Assets/Scripts/Entities/Enemies/Enemy.cs, Assets/Scripts/Entities/Enemies/Ghost.cs, Assets/Scripts/Entities/Enemies/Ghost.cs.meta, Assets/Scripts/PrefabManager.cs, ProjectSettings/TagManager.asset
Introduce a new ghost enemy. It move towards the player through the walls and stops when the player is in range.
When the ghost is moving, it can't take any damage. 
The ghost doesn't deal any contact damage (moving or not).
Close #98
=> Introduce new Ghost enemy

Assets/Scripts/Entities/Enemies/SpeedElite.cs, Assets/Scripts/Entities/Enemies/SpeedElite.cs.meta, Assets/Scripts/PrefabManager.cs
Add new type of elite ,the speed elite
Close #100
=> Add speed elite enemy

Assets/Scripts/Entities/Enemies/RegenElite.cs, Assets/Scripts/Entities/Enemies/RegenElite.cs.meta, Assets/Scripts/PrefabManager.cs
Add new elite type ,the regen type this elite regenerate one life point all three second
Close #101
=> Add regen elite enemy
